@MaelstromLauncher.Server_HostAddress = http://localhost:5183

// Gets the current game manifest with all file entries and metadata
GET {{MaelstromLauncher.Server_HostAddress}}/api/manifest
Accept: application/json

GET {{MaelstromLauncher.Server_HostAddress}}/api/manifest/info
Accept: application/json

GET {{MaelstromLauncher.Server_HostAddress}}/api/gamelauncher
Accept: application/octet-stream

GET {{MaelstromLauncher.Server_HostAddress}}/api/gamelauncher/status
Accept: application/json